- name: local git pull from github
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars.yml

  tasks:
  - name: Pull sources from the repository.
    git: repo={{ project_repo }} dest={{ project_dir }} version={{ branch }} remote=origin key_file={{ key_file }} update=yes
    notify: pull to demo server

  handlers:
    - include: handlers.yml
