---
- hosts: DemoServer
  vars_files:
    - vars.yml
  gather_facts: false
  sudo_user: project_name

  tasks:
  - name: Pull sources from the repository.
    git: repo={{ project_repo }} 
    	 dest={{ project_root }} 
    	 version={{ branch }} 
    	 key_file = {{ key_file }}
    	 update = yes
    	 remote = origin

  - name: Upgrade the virtualenv.
    pip: requirements={{ project_dir }}/requirements.txt virtualenv={{ project_dir }}/venv/

  - name: Upgrade database.
    shell: {{ project_dir }}/venv/bin/python {{ project_root }}/manage.py db upgrade

  - name: make web frontend.
  	shell: make
  	notify:
  		- restart supervisor project_name